resteasy:
  jaxrs:
    app:
      registration: property
      classes: io.weli.resteasy2168.springboot.MyApplication
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - shutdown
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    org:
      springframework: info